active_creator: expoparker
training_creators:
  - expoparker
  - cleoabram
  - gray.davis 
  - natsingssongs
  - darbleymiller
  - mickycashflow
  - puderschmude
test_creator: gray.davis
defaults:
  model_name: BAAI/bge-large-en-v1.5
  caption_limit: 30
  scan_limit: 100
  selection_mode: both
  selection_percentile: 0.2
  selection_metric: views
